spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog.yaml
  jpa:
    hibernate:
      properties:
        hibernate:
          show_sql: true
          format_sql: true
      ddl-auto: none
    database: h2
  datasource:
#    url: jdbc:mysql://localhost:3306/tenant_manager
#    username: root
#    password: root@123

    url: jdbc:h2:~/h2/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    connectionTimeout: 20000
    maxPoolSize: 10
    idleTimeout: 300000
    minIdle: 10
    poolName: tm-connection-pool
    username: sa
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type: trace


#Application Defined
traccar:
  base-url: http://localhost:8082/api
  admin:
    username: admin
    password: admin

